from __future__ import annotations

import argparse
import json
from pathlib import Path


REMOVE_IDS = {
    "cir_2025_07_fr_effective_date_02",
    "cir_2025_14_fr_effective_date_02",
}

UPDATES = {
    "cir_2025_14_fr_amount_or_rate_01": {
        "expected_answer": "Le taux d'intérêt préférentiel correspond au taux du marché monétaire, majoré d'une marge qui ne peut pas dépasser 1%.",
    },
    "cir_2025_15_fr_required_action_03": {
        "expected_answer": "La carte doit être remise au siège social de la Banque Centrale de Tunisie, au 25 rue Hédi Nouira, 1080 Tunis, ou à l'une de ses succursales les plus proches.",
    },
}

MANUAL_ITEMS = [
    {
        "id": "cir_2025_11_fr_seasonal_tomato_credit_01",
        "query": "Je cultive des tomates de saison. Quel est le plafond du crédit par hectare et à quelle date arrive-t-il à échéance ?",
        "language": "fr",
        "category": "amount_or_rate",
        "relevant": True,
        "expected_source": "Cir_2025_11_fr.pdf",
        "expected_page": 2,
        "expected_answer": "Le barème d'intervention est plafonné à 12 640 dinars par hectare et l'échéance est fixée au 31 juillet.",
        "evidence_quote": "- Tomate de saison\nHa\n12640\n31 Juillet",
    },
    {
        "id": "cir_2025_11_fr_northern_almond_credit_02",
        "query": "Quels plafonds de crédit s'appliquent à un hectare d'amandiers dans le Nord en sec et en irrigué, et quelle est l'échéance ?",
        "language": "fr",
        "category": "amount_or_rate",
        "relevant": True,
        "expected_source": "Cir_2025_11_fr.pdf",
        "expected_page": 2,
        "expected_answer": "Le plafond est de 2 835 dinars par hectare en sec et de 6 295 dinars en irrigué, avec une échéance au 31 août.",
        "evidence_quote": "- Amandiers au Nord\nHa\n2835\n6295\n31 Août",
    },
    {
        "id": "cir_2025_11_fr_credit_ceiling_adjustment_03",
        "query": "Une banque doit-elle accorder automatiquement la totalité du barème prévu pour un crédit agricole ?",
        "language": "fr",
        "category": "exception_or_condition",
        "relevant": True,
        "expected_source": "Cir_2025_11_fr.pdf",
        "expected_page": 3,
        "expected_answer": "Non. Le barème constitue un plafond et la banque doit moduler le crédit selon la taille de l'exploitation, les dépenses à engager et les rendements des dernières campagnes.",
        "evidence_quote": "Ce barème constitue un plafond. Le montant du crédit dispensé par la banque devra être modulé en fonction de la taille de l'exploitation, des dépenses à engager et des rendements réalisés au cours des dernières campagnes.",
    },
    {
        "id": "cir_2025_12_fr_remote_exchange_request_01",
        "query": "Comment une personne ou une entreprise peut-elle déposer à distance une demande d'autorisation pour une opération de change ?",
        "language": "fr",
        "category": "procedure_or_documents",
        "relevant": True,
        "expected_source": "Cir_2025_12_fr.pdf",
        "expected_page": 2,
        "expected_answer": "La demande est déposée sur la plateforme sécurisée https://exop.bct.gov.tn en remplissant le formulaire prévu et en téléchargeant les justificatifs indiqués dans le guide d'utilisation.",
        "evidence_quote": "La plateforme numérique est accessible via le lien suivant : https://exop.bct.gov.tn Article 3 - Les demandes d’autorisation sont déposées via la plateforme numérique en remplissant le formulaire prévu à cet effet. Les documents et les justificatifs requis doivent être téléchargés conformément au guide d’utilisation téléchargeable gratuitement sur la plateforme.",
    },
    {
        "id": "cir_2025_12_fr_authorization_types_02",
        "query": "Quelle décision est délivrée pour une opération de change avec transfert de fonds vers l'étranger, et laquelle s'applique sans transfert ?",
        "language": "fr",
        "category": "definition",
        "relevant": True,
        "expected_source": "Cir_2025_12_fr.pdf",
        "expected_page": 3,
        "expected_answer": "Une « autorisation de transfert » est délivrée lorsqu'il y a transfert de fonds vers l'étranger ou au profit d'un non-résident établi en Tunisie. Une simple « autorisation » est délivrée lorsque l'opération ne donne pas lieu à un tel transfert.",
        "evidence_quote": "sous forme d’« autorisation » pour les demandes d’autorisation relatives à des opérations de change ne donnant pas lieu à un transfert de fonds vers l’étranger ou au profit de non-résidents établis en Tunisie. - sous forme d’« autorisation de transfert » pour les demandes d’autorisation relatives à des opérations de change entraînant un transfert de fonds depuis la Tunisie vers l’étranger ou au profit de non-résidents établis en Tunisie.",
    },
    {
        "id": "cir_2025_12_fr_transfer_authorization_validity_03",
        "query": "Pendant combien de temps une autorisation de transfert de devises reste-t-elle valable si elle n'est pas utilisée ?",
        "language": "fr",
        "category": "deadline_or_duration",
        "relevant": True,
        "expected_source": "Cir_2025_12_fr.pdf",
        "expected_page": 3,
        "expected_answer": "Elle reste valable deux mois à compter de la date indiquée sur l'autorisation. Passé ce délai sans utilisation, elle devient nulle.",
        "evidence_quote": "L’autorisation de transfert délivrée par la Banque Centrale de Tunisie reste valable pendant deux mois à compter de la date de l’autorisation qui y est indiquée. L’autorisation de transfert non utilisée durant ce délai est considérée comme nulle.",
    },
    {
        "id": "cir_2025_12_fr_platform_only_deadline_04",
        "query": "À partir de quand les demandes d'autorisation d'opérations de change doivent-elles être déposées uniquement sur la plateforme numérique ?",
        "language": "fr",
        "category": "deadline_or_duration",
        "relevant": True,
        "expected_source": "Cir_2025_12_fr.pdf",
        "expected_page": 4,
        "expected_answer": "Après le 31 décembre 2025, seules les demandes déposées sur la plateforme numérique sont acceptées.",
        "evidence_quote": "Les demandeurs d’autorisation pour les opérations de change peuvent, jusqu’au 31 décembre 2025, présenter leurs demandes [...] A l’expiration du délai prévu par le présent article, seules les demandes d’autorisation déposées via la plateforme numérique seront acceptées.",
        "evidence_method": "visual_review",
    },
    {
        "id": "cir_2025_16_fr_pilgrimage_allowance_start_01",
        "query": "À partir de quelle date les guichets uniques peuvent-ils délivrer l'allocation touristique aux pèlerins de la campagne 2026 ?",
        "language": "fr",
        "category": "effective_date",
        "relevant": True,
        "expected_source": "Cir_2025_16_fr.pdf",
        "expected_page": 2,
        "expected_answer": "Les intermédiaires agréés peuvent délivrer cette allocation aux guichets uniques à compter du 10 décembre 2025.",
        "evidence_quote": "les Intermédiaires Agréés sont habilités à octroyer l’allocation touristique, à travers les guichets uniques, et ce à compter du 10 décembre 2025.",
    },
    {
        "id": "cir_2025_16_fr_pilgrimage_allowance_use_02",
        "query": "Une allocation touristique imputée sur les droits à transfert de 2026 peut-elle être utilisée avant le début de 2026 ?",
        "language": "fr",
        "category": "prohibition_or_limit",
        "relevant": True,
        "expected_source": "Cir_2025_16_fr.pdf",
        "expected_page": 2,
        "expected_answer": "Non. Une allocation imputée sur l'année 2026 ne peut pas être utilisée avant le début de 2026.",
        "evidence_quote": "Ces allocations touristiques à imputer sur l’année 2026 ne peuvent en aucun cas être utilisées au cours de l’année en cours.",
    },
    {
        "id": "cir_2025_16_fr_pilgrimage_export_validity_03",
        "query": "Combien de temps l'autorisation d'exporter des devises en billets pour le pèlerinage de 2026 reste-t-elle valable, et qui peut en bénéficier ?",
        "language": "fr",
        "category": "deadline_or_duration",
        "relevant": True,
        "expected_source": "Cir_2025_16_fr.pdf",
        "expected_page": 3,
        "expected_answer": "Elle reste valable six mois à compter de sa délivrance et concerne uniquement les pèlerins inscrits sur les listes officielles et les membres de la délégation tunisienne officielle qui les accompagne.",
        "evidence_quote": "l’autorisation d'exportation de devises en billets de banque au titre de l’allocation touristique demeure valable six mois à compter de la date de sa délivrance et ce, uniquement pour les pèlerins inscrits sur les listes officielles ainsi qu’aux membres de la délégation tunisienne officielle désignée pour les accompagner.",
    },
    {
        "id": "cir_2025_17_fr_risk_assessment_update_01",
        "query": "À quelle fréquence un établissement financier doit-il mettre à jour son évaluation des risques de blanchiment, de financement du terrorisme et de prolifération ?",
        "language": "fr",
        "category": "deadline_or_duration",
        "relevant": True,
        "expected_source": "Cir_2025_17_fr.pdf",
        "expected_page": 3,
        "expected_answer": "Le rapport doit être mis à jour au moins tous les trois ans, ou plus tôt lorsqu'un événement significatif, une information d'une autorité compétente ou un changement légal ou réglementaire modifie les facteurs de risque.",
        "evidence_quote": "Les évaluations des risques auxquels sont exposés les établissements assujettis doivent être consignées dans un rapport, mis à jour au moins tous les trois ans, ou plus fréquemment en cas de survenance d’un événement significatif affectant les facteurs de risque, ou lorsque des informations émanant des autorités compétentes sont susceptibles de modifier l’évaluation des risques inhérents, notamment en cas de changement légal ou réglementaire ou de mise à jour de l’évaluation nationale des risques.",
    },
    {
        "id": "cir_2025_17_fr_proliferation_financing_risk_02",
        "query": "Qu'est-ce qu'un risque de financement de la prolifération des armes de destruction massive ?",
        "language": "fr",
        "category": "definition",
        "relevant": True,
        "expected_source": "Cir_2025_17_fr.pdf",
        "expected_page": 4,
        "expected_answer": "Il s'agit d'un manquement potentiel, d'une non-application ou d'un contournement des sanctions financières ciblées prévues par les résolutions du Conseil de sécurité de l'ONU, notamment le gel sans délai des avoirs et l'interdiction de mettre des fonds ou biens à la disposition d'une personne ou entité désignée.",
        "evidence_quote": "Est considéré risque de financement de la prolifération des armes de destruction massive [...] tout manquement potentiel, non-application ou contournement des obligations de sanctions financières ciblées prévues par les résolutions du Conseil de sécurité des Nations Unies. Ces obligations portent notamment sur le gel sans délai des fonds et autres biens, ainsi que sur l’interdiction de mettre des fonds ou autres biens à la disposition ou au bénéfice de toute personne ou entité désignée",
        "evidence_method": "visual_review",
    },
    {
        "id": "cir_2025_17_fr_ctaf_designation_deadline_03",
        "query": "Dans quel délai un établissement assujetti doit-il transmettre à la Banque Centrale la désignation de son correspondant CTAF et de son suppléant ?",
        "language": "fr",
        "category": "deadline_or_duration",
        "relevant": True,
        "expected_source": "Cir_2025_17_fr.pdf",
        "expected_page": 4,
        "expected_answer": "Une copie de la décision de désignation doit être transmise dans les cinq jours suivant la date de désignation.",
        "evidence_quote": "Une copie de la décision portant désignation du correspondant de la CTAF et de son suppléant est adressée à la Banque Centrale de Tunisie dans un délai ne dépassant pas cinq (5) jours à compter de la date de désignation.",
    },
    {
        "id": "cir_2025_17_fr_suspicious_transaction_channel_04",
        "query": "Par quel canal un établissement assujetti doit-il déclarer une opération ou transaction suspecte, et dans quel délai ?",
        "language": "fr",
        "category": "reporting_or_control",
        "relevant": True,
        "expected_source": "Cir_2025_17_fr.pdf",
        "expected_page": 4,
        "expected_answer": "Il doit la déclarer immédiatement au moyen de la plateforme goAML, selon les procédures et mesures techniques définies par la CTAF.",
        "evidence_quote": "Les établissements assujettis doivent déclarer immédiatement les opérations et les transactions suspectes via la plateforme goAML, conformément aux procédures et aux mesures techniques définies par la CTAF.",
    },
    {
        "id": "cir_2025_17_fr_frozen_assets_reporting_05",
        "query": "Dans quel délai l'état trimestriel des avoirs gelés doit-il être transmis à la Banque Centrale, et quels gels couvre-t-il ?",
        "language": "fr",
        "category": "reporting_or_control",
        "relevant": True,
        "expected_source": "Cir_2025_17_fr.pdf",
        "expected_page": 5,
        "expected_answer": "Il doit être transmis au plus tard vingt jours ouvrables après la fin de chaque trimestre. Il couvre les gels liés aux sanctions de l'ONU, ceux décidés par la Commission nationale de lutte contre le terrorisme et ceux liés au financement de la prolifération.",
        "evidence_quote": "Les établissements assujettis sont tenus de transmettre à la Banque Centrale de Tunisie un état trimestriel des avoirs gelés [...] Les gels au titre des sanctions onusiennes ; et - Les gels décidés par la Commission Nationale de Lutte contre le Terrorisme. Cette obligation couvre également les gels opérés dans le cadre de la lutte contre le financement de la prolifération des armes de destruction massive. Ledit état doit être conforme à l’annexe 6 [...] et transmis dans un délai maximum de vingt (20) jours ouvrables suivant la fin de chaque trimestre.",
        "evidence_method": "visual_review",
    },
    {
        "id": "note_2025_03_ar_issuer_codes_01",
        "query": "ما هي الرموز المسندة إلى شركات « ALICE CRECHE FAYACHE NAWEL » و« ALICE » و« ALICE PLUS » و« MYTEK INFORMATIQUE »؟",
        "language": "ar",
        "category": "definition",
        "relevant": True,
        "expected_source": "Note_2025_03_ar.pdf",
        "expected_page": 1,
        "expected_answer": "الرموز هي 0151 لشركة « ALICE CRECHE FAYACHE NAWEL »، و0152 لشركة « ALICE »، و0153 لشركة « ALICE PLUS »، و0154 لشركة « MYTEK INFORMATIQUE ».",
        "evidence_quote": "0151 شركة «ALICE CRECHE FAYACHE NAWEL» 0152 شركة «ALICE» 0153 شركة «ALICE PLUS» 0154 شركة «MYTEK INFORMATIQUE»",
    },
    {
        "id": "note_2025_142_fr_fifty_dinar_issue_01",
        "query": "Quand le nouveau billet tunisien de cinquante dinars de type 2022 a-t-il été mis en circulation ?",
        "language": "fr",
        "category": "effective_date",
        "relevant": True,
        "expected_source": "Note_2025_142_fr.pdf",
        "expected_page": 1,
        "expected_answer": "Il a été mis en circulation à compter du 23 septembre 2025.",
        "evidence_quote": "La Banque Centrale de Tunisie met en circulation, à compter du 23 septembre 2025, un nouveau billet de banque de cinquante dinars (type 2022).",
        "evidence_method": "visual_review",
    },
    {
        "id": "note_2025_142_fr_fifty_dinar_concurrent_02",
        "query": "Le nouveau billet tunisien de cinquante dinars de type 2022 remplace-t-il immédiatement les autres billets de même type ?",
        "language": "fr",
        "category": "exception_or_condition",
        "relevant": True,
        "expected_source": "Note_2025_142_fr.pdf",
        "expected_page": 2,
        "expected_answer": "Non. Il circule en même temps que les autres billets de cinquante dinars de même type déjà en circulation.",
        "evidence_quote": "Le billet de banque de cinquante dinars (type 2022) [...] circulera concurremment avec les autres billets de même dénomination et de même type actuellement en circulation.",
        "evidence_method": "visual_review",
    },
    {
        "id": "note_2025_152_ar_peps_fitness_code_01",
        "query": "ما هو الرمز المسند إلى « STE PEPS FITNESS » في مصنفة مصدري الاقتطاعات البنكية والبريدية؟",
        "language": "ar",
        "category": "definition",
        "relevant": True,
        "expected_source": "Note_2025_152_ar.pdf",
        "expected_page": 1,
        "expected_answer": "الرمز المسند إلى « STE PEPS FITNESS » هو 0193.",
        "evidence_quote": "0193 « STE PEPS FITNESS »",
    },
    {
        "id": "note_2025_163_fr_ten_dinar_issue_01",
        "query": "Quand le nouveau billet tunisien de dix dinars de type 2020 a-t-il été mis en circulation ?",
        "language": "fr",
        "category": "effective_date",
        "relevant": True,
        "expected_source": "Note_2025_163_fr.pdf",
        "expected_page": 1,
        "expected_answer": "Il a été mis en circulation à compter du 17 octobre 2025.",
        "evidence_quote": "La Banque Centrale de Tunisie met en circulation, à compter du 17 octobre 2025, un nouveau billet de banque de dix dinars (type 2020).",
        "evidence_method": "visual_review",
    },
    {
        "id": "note_2025_163_fr_ten_dinar_issue_date_02",
        "query": "Quelle date d'émission figure sur le nouveau billet tunisien de dix dinars de type 2020 mis en circulation en octobre 2025 ?",
        "language": "fr",
        "category": "definition",
        "relevant": True,
        "expected_source": "Note_2025_163_fr.pdf",
        "expected_page": 2,
        "expected_answer": "La date d'émission imprimée sur ce billet est le 25-07-2025.",
        "evidence_quote": "De la date d’émission : remplacée par « 25-07-2025 » au lieu de « 20-3-2020 »",
    },
    {
        "id": "note_2025_168_ar_kidzy_ben_code_01",
        "query": "ما هو الرمز المسند إلى « KIDZY BEN » في مصنفة مصدري الاقتطاعات البنكية والبريدية؟",
        "language": "ar",
        "category": "definition",
        "relevant": True,
        "expected_source": "Note_2025_168_ar.pdf",
        "expected_page": 1,
        "expected_answer": "الرمز المسند إلى « KIDZY BEN » هو 0194.",
        "evidence_quote": "0194 « KIDZY BEN »",
    },
    {
        "id": "note_2025_175_ar_strike_continuity_01",
        "query": "ما التدابير التي يجب على البنوك اتخاذها لضمان السحب والدفع الإلكتروني خلال الإضراب القطاعي يومي 3 و4 نوفمبر 2025؟",
        "language": "ar",
        "category": "required_action",
        "relevant": True,
        "expected_source": "Note_2025_175_ar.pdf",
        "expected_page": 1,
        "expected_answer": "يجب ضمان استمرارية السحب من الشبابيك والموزعات الآلية والدفع الإلكتروني، وتأمين تزويد الموزعات بالنقد وجاهزية المنصات التقنية، مع معالجة الأعطال بسرعة وتوفير الحد الأدنى من الموارد البشرية.",
        "evidence_quote": "استمراريّة عمليّات السّحب من الشبابيك والموزّعات الآليّة للأوراق النقديّة وعمليّات الدفع الإلكتروني [...] بتأمين التزويد المستمر لهذه الموزّعات والسهر على حسن جاهزية المنصات التقنية المؤمنة لخدمات الدفع االلكتروني [...] التفاعل في اإلبان لمعالجة أي عطب أو انقطاع للخدمات مع توفير الموارد البشرية الالزمة لضمان الحد األدنى من الخدمات",
        "evidence_method": "visual_review",
    },
    {
        "id": "note_2025_175_ar_same_day_cash_supply_02",
        "query": "هل تستطيع البنوك طلب التزود بالنقد اليدوي من فروع البنك المركزي في اليوم نفسه خلال إضراب 3 و4 نوفمبر 2025؟",
        "language": "ar",
        "category": "exception_or_condition",
        "relevant": True,
        "expected_source": "Note_2025_175_ar.pdf",
        "expected_page": 1,
        "expected_answer": "نعم. تستجيب فروع البنك المركزي لطلبات التزود بالنقد اليدوي في اليوم نفسه خلال تلك الفترة، استثناء من الضوابط العادية.",
        "evidence_quote": "االستجابة لطلبات التزود بالنقد اليدوي في نفس اليوم، استثناء ألحكام المذكرة إلى البنوك والديوان الوطني للبريد عدد 129 لسنة 2024",
        "evidence_method": "visual_review",
    },
    {
        "id": "note_2025_195_ar_tunisianet_code_01",
        "query": "ما هو الرمز المسند إلى « TUNISIANET » في مصنفة مصدري الاقتطاعات البنكية والبريدية؟",
        "language": "ar",
        "category": "definition",
        "relevant": True,
        "expected_source": "Note_2025_195_ar.pdf",
        "expected_page": 1,
        "expected_answer": "الرمز المسند إلى « TUNISIANET » هو 0195.",
        "evidence_quote": "0195 « TUNISIANET »",
    },
    {
        "id": "note_2025_199_fr_regulatory_tag_01",
        "query": "Quelle balise réglementaire les banques doivent-elles intégrer dans tous les messages Swift pacs.008 émis en devises ?",
        "language": "fr",
        "category": "required_action",
        "relevant": True,
        "expected_source": "Note_2025_199_fr.pdf",
        "expected_page": 1,
        "expected_answer": "Elles doivent intégrer la balise <RglttryRptg> dans tous les messages Swift pacs.008 émis en devises.",
        "evidence_quote": "Les banques et l’Office National des Postes sont tenus d’intégrer la balise <RglttryRptg> dans tous les messages Swift pacs.008 émis en devises",
    },
    {
        "id": "note_2025_199_fr_account_nomenclature_02",
        "query": "Quelles informations doivent figurer dans la nomenclature actualisée des comptes clientèle transmise pour FIN MONITOR ?",
        "language": "fr",
        "category": "reporting_or_control",
        "relevant": True,
        "expected_source": "Note_2025_199_fr.pdf",
        "expected_page": 2,
        "expected_answer": "La nomenclature doit indiquer le code produit, le libellé du compte, sa devise, le type de client et son statut de résidence.",
        "evidence_quote": "la nomenclature actualisée des comptes clientèle comportant : • Code produit ; • Libellé du compte ; • Devise du compte ; • Type de client ; • Statut de résidence.",
    },
    {
        "id": "note_2025_199_fr_swift_archive_03",
        "query": "Depuis quelle année l'archive des messages Swift Alliance Access doit-elle être fournie à la Banque Centrale ?",
        "language": "fr",
        "category": "deadline_or_duration",
        "relevant": True,
        "expected_source": "Note_2025_199_fr.pdf",
        "expected_page": 2,
        "expected_answer": "Les banques et l'Office national des postes doivent fournir l'archive Swift Alliance Access depuis 2015.",
        "evidence_quote": "Les banques et l’Office National des Postes doivent fournir à la Banque Centrale de Tunisie l’archive des messages Swift Alliance Access depuis 2015.",
    },
    {
        "id": "note_2025_199_fr_incoming_swift_rules_04",
        "query": "Comment renseigner <DbtCdtRptgInd> et <Inf> dans un message Swift pacs.008 reçu de l'étranger ?",
        "language": "fr",
        "category": "procedure_or_documents",
        "relevant": True,
        "expected_source": "Note_2025_199_fr.pdf",
        "expected_page": 3,
        "expected_answer": "<DbtCdtRptgInd> doit contenir CRED ou BOTH, tandis que la sous-balise <Inf> ne doit pas être renseignée.",
        "evidence_quote": "Pour les messages Swift pacs.008 reçus de l’étranger : • <DbtCdtRptgInd> doit être CRED ou BOTH ; • La sous-balise <Inf> ne doit pas être renseignée",
    },
    {
        "id": "note_2025_199_fr_compliance_deadline_05",
        "query": "Quel délai les banques et l'Office national des postes ont-ils pour se conformer aux exigences de la nouvelle version de FIN MONITOR ?",
        "language": "fr",
        "category": "deadline_or_duration",
        "relevant": True,
        "expected_source": "Note_2025_199_fr.pdf",
        "expected_page": 3,
        "expected_answer": "Ils disposent de trois mois à compter de la date de publication.",
        "evidence_quote": "Les établissements bancaires ainsi que l’Office National des Postes sont tenus de se conformer aux dispositions de la présente note dans un délai de trois (03) mois à compter de sa date de publication.",
    },
]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    items = json.loads(args.input.read_text(encoding="utf-8"))
    curated = []
    for item in items:
        if item["id"] in REMOVE_IDS:
            continue
        item = dict(item)
        item.update(UPDATES.get(item["id"], {}))
        item["evidence_method"] = "text_extraction"
        curated.append(item)
    for item in MANUAL_ITEMS:
        item = dict(item)
        item.setdefault("evidence_method", "text_extraction")
        curated.append(item)
    curated.sort(key=lambda item: (item["expected_source"].casefold(), item["id"]))
    args.output.write_text(
        json.dumps(curated, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"curated {len(items)} generated items into {len(curated)} reviewed items")


if __name__ == "__main__":
    main()
